services:
  node_server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    environment:
      - NODE_ENV=Production
      - PORT=5000
  node_server_2:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server_2
    environment:
      - NODE_ENV=Production
      - PORT=5001

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - node_server
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx
